# Generated by Django 4.1.3 on 2022-11-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
