# Generated by Django 4.1.3 on 2022-11-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanishapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
            ],
        ),
    ]
